apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-root
  name: busybox-root
spec:
  containers:
  - image: busybox
    name: busybox-root
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2
        memory: 512Mi
    args:
      - /bin/sh
      - -c
      - >
        id;
        while true; do echo ".";sleep 5; done;
  restartPolicy: Never