apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-2
  name: busybox-stress-2
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: busybox-2
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 1500m 
    args:
      - /bin/sh
      - -c
      - >
        for i in $(seq 1 40); do 
            while true; do wget -O index.html http://nginx; done & 
        done;
        while true; do echo -n ".";sleep 5; done

# run watch kubectl top pod to see the CPU usage