apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-2
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 2
  - image: busybox
    name: busybox
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 2
  restartPolicy: Never
