apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-2
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
  - image: busybox
    name: busybox
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1500m
        memory: 1Gi
  restartPolicy: Never
